export const PAGE_NAMES = {
  SIGN_UP: 'signUp',
  SIGN_IN: 'signIn',
  HOME: 'home',
  PROFILE_READ: 'profileRead',
  PROFILE_EDIT: 'profileEdit',
  PROFILE_CHANGE_PASS: 'profileChangePass',
  PROFILE_CHANGE_AVATAR: 'profileChangeAvatar',
  PROFILE_CHANGE_AVATAR_ERROR: 'profileChangeAvatarError',
  PROFILE_CHANGE_AVATAR_UPLOADED: 'profileChangeAvatarUploaded',
  MESSENGER: 'messenger',
  500: '500',
  400: '400',
  404: '404',
} as const;
